In [1]:
import sys
import os

# Add the parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), os.pardir)))

In [2]:
import gymnasium as gym
import numpy as np

from controllers import PIDController

/home/giulio/prog/.virtualenvs/ctrl/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
env = gym.make('Pendulum-v1')
    
# Initialize controller
controller = PIDController(kp=1.0, ki=0.5, kd=0.1)

# Simulation loop
state, info = env.reset()
done = False

In [4]:
state

array([ 0.86431086, -0.50295794,  0.26549038], dtype=float32)

In [5]:
env.render()
print(state)
cos_theta, sin_theta, theta_dot = state
angle = np.arctan2(sin_theta, cos_theta)

[ 0.86431086 -0.50295794  0.26549038]


/home/giulio/prog/.virtualenvs/ctrl/lib/python3.8/site-packages/gymnasium/envs/classic_control/pendulum.py:173: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("Pendulum-v1", render_mode="rgb_array")
  gym.logger.warn(


In [6]:
control_action = controller.compute_action(angle, reference=0)
state, reward, done, truncated, _ = env.step([control_action])
env.close()

In [7]:
env.step([control_action])

(array([ 0.85870713, -0.51246667, -0.23549965], dtype=float32),
 -0.27770332045772994,
 False,
 False,
 {})

In [8]:
best_params = controller.tune(env)
print(f"Best parameters: {best_params}")

[I 2023-10-30 12:46:05,929] A new study created in memory with name: no-name-0c6d2f01-36ca-45fa-83bf-489ae5759901
[I 2023-10-30 12:46:05,948] Trial 0 finished with value: 157.68606369126798 and parameters: {'kp': 4.118467553758391, 'ki': 0.32253777534087924, 'kd': 0.7637859452967144}. Best is trial 0 with value: 157.68606369126798.
[I 2023-10-30 12:46:05,963] Trial 1 finished with value: 229.04158444936274 and parameters: {'kp': 0.08630934870759721, 'ki': 1.410188583804426, 'kd': 3.042217974873043}. Best is trial 0 with value: 157.68606369126798.
[I 2023-10-30 12:46:05,979] Trial 2 finished with value: 163.48145173528735 and parameters: {'kp': 0.6999856913078883, 'ki': 1.6937256964280296, 'kd': 4.242625187482554}. Best is trial 0 with value: 157.68606369126798.
[I 2023-10-30 12:46:05,991] Trial 3 finished with value: 236.12432000564795 and parameters: {'kp': 4.418537165555181, 'ki': 1.8576439026186713, 'kd': 2.3049255780373623}. Best is trial 0 with value: 157.68606369126798.
[I 2023-1

Best parameters: {'kp': 4.435803692748082, 'ki': 3.9879963505275615, 'kd': 0.025572681481249804}


In [9]:
best_params

{'kp': 4.435803692748082, 'ki': 3.9879963505275615, 'kd': 0.025572681481249804}