In [1]:
import sys
import os

# Add the parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), os.pardir)))

In [2]:
import gymnasium as gym
import numpy as np

from controllers import PIDController

In [3]:
env = gym.make('Pendulum-v1')
    
# Initialize controller
controller = PIDController(kp=1.0, ki=0.5, kd=0.1)

# Simulation loop
state, info = env.reset()
done = False

In [4]:
state

array([-0.2601433 , -0.96557003, -0.35910955], dtype=float32)

In [5]:
env.render()
print(state)
cos_theta, sin_theta, theta_dot = state
angle = np.arctan2(sin_theta, cos_theta)

[-0.2601433  -0.96557003 -0.35910955]


/home/giulio/prog/.virtualenvs/ctrl/lib/python3.8/site-packages/gymnasium/envs/classic_control/pendulum.py:173: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("Pendulum-v1", render_mode="rgb_array")
  gym.logger.warn(


In [9]:
control_action = controller.compute_action(angle, reference=0)
state, reward, done, truncated, _ = env.step([control_action])
env.close()

In [8]:
env.step([control_action])

(array([-0.35442445, -0.93508464, -1.1992699 ], dtype=float32),
 -3.573974731282407,
 False,
 False,
 {})